name: 'action-standard-version'
description: 'create CHANGELOG.md and tag by https://github.com/conventional-changelog/standard-version'
inputs:
  release-by-ref:
    description: 'release branch as release-{MAJOR}.{MINOR}.{PATCH}-{Backus–Naur} and set by github.head_ref'
    required: true
  push-changes-and-tag:
    description: 'after make change lop then push change and tags to remote'
    required: true
  dry-run:
    description: 'See the commands that running'
    required: false
  target-branch:
    description: 'tag branch to push default is env by GITHUB_REF'
    default: ''
    required: false
  release-as:
    description: 'Specify the release type manually. if set this will override the `release-by-ref` input'
    default: ''
    required: false
  release-ref-regexp:
    description: 'release ref regexp or setting as release\-(.*)(\-)+([\w].*)+'
    default: '.*release\-(\w.*)'
    required: false
  tag-prefix:
    description: 'tag prefix'
    default: 'v'
    required: false
  release-tag-name-env:
    description: 'release tag name env'
    default: 'ACTION_STANDARD_VERSION_RELEASE_TAG_NAME'
    required: false

outputs:
  release-tag-name: # output will be available to future steps
    description: 'release tag name'
  release-tag-short:
    description: 'release tag without tag prefix'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: purple
  icon: tag