# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: node-ci

on:
  workflow_call: # https://docs.github.com/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow

jobs:
  node-ci:
    name: node-ci
    defaults:
      run:
        shell: bash
       # working-directory: ${{ env.WORK_DIR }}
    strategy:
      matrix:
        node-version: # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          # - 'lts/*'
          - '20.x'
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      -
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      -
        name: Install dependencies
        run: |
          node -v
          npm install
          npm ci

      -
        name: Test with node
        run: |
          npm test
      -
        name: Test coverage
        run: |
          npm run jest:coverage
      -
        name: Build if present
        run: |
          npm run build --if-present
